[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.6",
    "flask>=3.1.0",
    "pydantic>=2.10.4",
    "requests>=2.32.3",
]
